language: python
sudo: false
python:
  - "3.5"
  - "pypy3"
  - "3.6"
env:
  global: PYTHONHASHSEED=random
cache:
  directories:
    - $HOME/.cache/pip
script:
  - pip install pip --upgrade
  - python -m unittest dystros.tests.test_suite

